//! Local registry helpers for the Atomic Swap contract.
//!
//! # Role
//!
//! This module is **not** an independent IP registry.  It is a thin
//! cross-contract adapter that the Atomic Swap contract uses to reach the
//! canonical `ip_registry` contract deployed separately on Stellar.
//!
//! Specifically it:
//!
//! * Reads the `ip_registry` contract address that was stored in Atomic Swap's
//!   own instance storage at initialisation time (under [`DataKey::IpRegistry`]).
//! * Exposes convenience wrappers — [`ensure_seller_owns_active_ip`] and
//!   [`verify_commitment`] — so swap logic can call into `ip_registry` without
//!   repeating the address-lookup boilerplate at every call site.
//!
//! # Relationship to `ip_registry`
//!
//! ```text
//!  AtomicSwap contract
//!       │
//!       │  calls via IpRegistryClient (generated by soroban-sdk)
//!       ▼
//!  ip_registry contract  (separate Wasm, separate address)
//!       │
//!       └── owns the canonical IpRecord storage (owner, hash, timestamp, revoked)
//! ```
//!
//! `registry.rs` never stores IP ownership records itself — it always delegates
//! to the authoritative `ip_registry` contract.  If you need to read or write
//! IP state, use the `ip_registry` contract directly; this module only provides
//! guarded read helpers that panic with a typed [`ContractError`] when
//! ownership or revocation constraints are violated.

use soroban_sdk::{Address, BytesN, Env};

use crate::{utils::panic_with_error, ContractError, DataKey};

pub fn ip_registry(env: &Env) -> Address {
    env.storage()
        .instance()
        .get(&DataKey::IpRegistry)
        .unwrap_or_else(|| panic_with_error(env, ContractError::NotInitialized))
}

pub fn ensure_seller_owns_active_ip(env: &Env, ip_id: u64, seller: &Address) {
    let registry_addr = ip_registry(env);
    let registry = ip_registry::IpRegistryClient::new(env, &registry_addr);
    let record = registry.get_ip(&ip_id);

    if record.owner != *seller {
        panic_with_error(env, ContractError::NotIPOwner);
    }

    if record.revoked {
        panic_with_error(env, ContractError::IpRevoked);
    }
}

pub fn verify_commitment(
    env: &Env,
    ip_id: u64,
    secret: &BytesN<32>,
    blinding_factor: &BytesN<32>,
) -> bool {
    let registry_addr = ip_registry(env);
    let registry = ip_registry::IpRegistryClient::new(env, &registry_addr);
    registry.verify_commitment(&ip_id, secret, blinding_factor)
}
